### ISSUE TITLE
Transaction detailed view

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#100]
As a user I have clicked "+" More info on the pending transaction screen and I am shown the transaction details

- [ ] Beneficiary
- [ ] Amount
- [ ] Execution Date
- [ ] Time
- [ ] Notes

The back arrow takes me back to the pending transactions list

https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/351492543

**Comment by webmaster128** [comment]
As discussed in https://github.com/iov-one/ponferrada/issues/155#issuecomment-491788445, it is simpler to only have one type of transaction (currently names `ProcessedTx`) that can handle both pending and executed transactions. We need to track a transaction's state anyway (signed, posted, accepted by node, in block, number of confirmations). Thus I change the title from "Pending Transaction detailed view" to just "Transaction detailed view". I think we should only have one screen to show all available detail of a `ProcessedTx`.

**Comment by kmw101** [comment]
This is done in the calling application (wallet)
