### ISSUE TITLE
Starname in Wallet: Registration flow

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1001]
Figma design:
https://www.figma.com/file/iF4KASslEFOzazuwzixKOm/Neuma-Wallet-Design-Changes
(Current iteration page)

- [x] Registration form is the same as in case of iovnames
- [x] in the "Register your starname" field, the placeholder text is: `eg. *starname`
- [x] if a starname is not available because it has been already registered or is a trade mark, an error message is shown just like in the design: `Sorry, but this starname is not available`
- [x] The hint (question mark) next to the `Choose linked addresses` will open a modal explaining what linked addresses mean (just as seen in the design)
- [x] The hint (question mark) next to the `How it works` will open a modal explaining what a starname is (just as seen in the design)
- [x] implement request for registration for Neuma extension

<img width="1440" alt="Neuma Wallet - Register Starname (1)" src="https://user-images.githubusercontent.com/7419692/73850950-fe464380-482c-11ea-9ea2-4cf527cce685.png">

<img width="1440" alt="Neuma Wallet - Register Starname - error message" src="https://user-images.githubusercontent.com/7419692/73850975-0aca9c00-482d-11ea-93ac-b33bae82fbab.png">

<img width="1440" alt="Neuma Wallet - Register Starname (2)" src="https://user-images.githubusercontent.com/7419692/73850989-0ef6b980-482d-11ea-9f26-d2ab5460b0b6.png">

**Comment by abefernan** [comment]
The "after the user goes through the registration flow without an error, the starname should be registered and visible in the "Your starnames" section" checkbox is part of #1006.
