### ISSUE TITLE
Starname in Wallet: Manage iovnames/starnames/names

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1004]
Figma design:
https://www.figma.com/file/iF4KASslEFOzazuwzixKOm/Neuma-Wallet-Design-Changes?node-id=1177%3A1852
(Current iteration page)

**iovnames:**
- [x] if a user wants to manage an iovname and clicks on the "Manage" on that iovname, the user will be navigated to the manage iovname screen
- [x] the owner of the iovname will be able to edit the account targets (addresses) by clicking the Edit button 
- [x] the owner of the iovname will be able to do more actions with the iovname, if he clicks on the "..." icon next to the "Edit"
- [x] the owner of the iovname will be able to Renew, Transfer or Delete the iovname
- [x] the Renew action takes the user to the renew flow
- [x] the Transfer action takes the user to the transfer flow
- [x] the Delete action takes the user to the delete flow

**starnames and names:**
- [x] if a user wants to manage an starname/name and clicks on the "Manage" on that starname/name, the user will be navigated to the manage starname/name screen

Please refer to what a domain admin or an account owner can do regarding starnames/names and actions (like transfer, delete, renew):
https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/account/README.md

_account owner:_
- [x] the account owner will be able to edit the account targets (addresses) by clicking the Edit button 
- [x] the account owner will be able to do more actions with the name, if he clicks on the "..." icon next to the "Edit"
- [x] the account owner will be able to Delete the name under a domain

_domain admin:_ 
- [x] the domain admin will be able to edit the targets (addresses) by clicking the Edit button  
- [x] the domain admin will be able to do more actions with the domain/accounts, if he clicks on the "..." icon next to the "Edit"
- [x] the domain admin will be able to Renew, Transfer, Delete the domain
- [x] the Renew action takes the user to the renew flow
- [x] the Transfer action takes the user to the transfer flow
- [x] the Delete action takes the user to the delete flow
- [x] the domain admin will be able to Transfer and Delete an account in the domain
- [x] the domain admin will be able to Transfer, Transfer back to him and Delete an already assigned account in the domain
- [x] the domain admin can create a name under a domain by clicking on "Create a new name" under the domain details

<img width="1440" alt="Neuma Wallet - Your iovnames - filled" src="https://user-images.githubusercontent.com/7419692/74134653-2e099880-4beb-11ea-83c2-8093509cec05.png">

<img width="1440" alt="Neuma Wallet - Your iovnames - Manage" src="https://user-images.githubusercontent.com/7419692/74134654-2fd35c00-4beb-11ea-848d-597f96d86825.png">

<img width="1440" alt="Neuma Wallet - Your iovnames - Edit name" src="https://user-images.githubusercontent.com/7419692/74134657-31048900-4beb-11ea-9e9b-2c408764c514.png">

<img width="1440" alt="Neuma Wallet - Addresses - Manage (1)" src="https://user-images.githubusercontent.com/7419692/74654473-a4c60900-518a-11ea-93b9-028d34de9ad4.png">

<img width="1440" alt="Neuma Wallet - Starnames - Edit Starname (1)" src="https://user-images.githubusercontent.com/7419692/74654884-99bfa880-518b-11ea-90a9-5ad87c37f23d.png">

<img width="1440" alt="Neuma Wallet - Starnames - Edit Targets" src="https://user-images.githubusercontent.com/7419692/74654889-9b896c00-518b-11ea-9fa4-f73e948f775d.png">

<img width="1440" alt="Neuma Wallet - Addresses - Edit Starname" src="https://user-images.githubusercontent.com/7419692/74654895-9d532f80-518b-11ea-827f-c7c485e9b9bd.png">

**Comment by albertandrejev** [comment]
Can not continue until https://github.com/iov-one/ponferrada/issues/1006 will be implemented.
