### ISSUE TITLE
Starname in Wallet: List of registered iovnames/starnames/names

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1006]
Figma design:
https://www.figma.com/file/iF4KASslEFOzazuwzixKOm/Neuma-Wallet-Design-Changes
(Current iteration page)

iovnames:
- [x] new icon and text for registering an iovname: "Register a new iovname" and a link next to it "Register now"
- [x] "Register now" takes the user to the iovname registration flow
- [x] iovnames can be managed by clicking on the "Manage" link which takes the user to the managing iovnames page

starnames and names:
- [x] under Addresses, in the "Your starnames", the user can see his registered starnames and names with their expiration dates
- [x] new icon and text for registering a starname: "Register a new starname" and a link next to it "Register now"
- [x] "Register now" takes the user to the starname registration flow
- [x] starnames or names can be managed by clicking on the "Manage" link which takes the user to the managing starnames/names page

<img width="1440" alt="Neuma Wallet - Your Starnames - Filled" src="https://user-images.githubusercontent.com/7419692/74644746-0c725900-5177-11ea-9ef7-f1f51d54b649.png">
<img width="1440" alt="Neuma Wallet - Your iovnames - filled (1)" src="https://user-images.githubusercontent.com/7419692/74644748-0d0aef80-5177-11ea-85ba-f21a95d75783.png">

**Comment by abefernan** [comment]
Regarding "under Addresses, in the "Your iovnames", the user can see his registered iovnames with their expiration dates", bns `usernames` (iovnames) have no associated expiry date or `validUntil`, as it is called in `accounts`. When the migration from usernames to accounts for iovnames happens, it will be added.
