### ISSUE TITLE
Clean bierzo-wallet welcome and payments view

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#103]
**Description**
The `bierzo-wallet` project as it is has all parts to be a decent app but we need to polish it a bit.

Things to do:
- [x] Transform the welcome view into something minimalistic like [this](https://drive.google.com/file/d/1bNJP5tIXwn2FW10gIfUSCjSAzjpNCIMQ/view?usp=sharing) Basically the icon in the middle of the circle should be the IOV's logo. And the grey colour should be our palette's main.
- [x] Introduce HMR in reducers as well see [here](https://github.com/iov-one/ponferrada/blob/master/packages/sanes-chrome-extension/src/store/index.ts#L15) and [here](https://github.com/iov-one/ponferrada/blob/master/packages/sanes-chrome-extension/src/store/index.ts#L9)
- [x] The codification of the main view's layout should be done following the semantic approach. Which means not using htmls tags, just container components like (Block, Grid...) available in medulas-react-components. 
- [x] Create your first DOM test assuring when you click on the button in welcome view, you travel to send payments.
- [x] Stop using Muli Light and go back to Muli.
- [x] Introduce validation in the send payment form and hardcoded values on the dropdown.
- [x] Create one storybook story for each view

**Comment by kmw101** [comment]
Issue is done
