### ISSUE TITLE
Validate address for each chain ID

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1054]
Problem: now, in the bitcoin address, we can write eg. `HELLOHELLO` , which is not a valid bitcoin address.

Can we add validation for addresses so only valid ones can be accepted for all the chain?

**Comment by albertandrejev** [comment]
Address validation is implemented on IOV Core level. We can implement regexp address validation for every supported blockchain. We need to add regexp into Chain ID configuration of every chain.

**Comment by antoineherzog** [comment]
Ideally we need validation on the @iov/bns package for each chainId

**Comment by albertandrejev** [comment]
Yes, I know. But didn't it means that we should implement support of those chains in IOV Core? Also, do we need support of this in @iov/bns or like other chains in separate package like @iov/ethereum or @iov/lisk?

**Comment by albertandrejev** [comment]
I need to know regexp for all supported chains to continue with validation. @davepuchyr

**Comment by davepuchyr** [comment]
> I need to know regexp for all supported chains to continue with validation. @davepuchyr

Please use the chain id list at https://docs.iov.one/docs/iov-name-service/clients/chain-ids.

**Comment by albertandrejev** [comment]
@davepuchyr But where to get regular expressions for all of those networks to verify address?

**Comment by davepuchyr** [comment]
Let's keep it simple and not use regular expressions for the time being.  Please validate against all the ids, both old and new, listed in https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/datamigration.go#L268.

**Comment by albertandrejev** [comment]
So what Chain IDs should we use in the wallet config? Old or new?

**Comment by davepuchyr** [comment]
> So what Chain IDs should we use in the wallet config? Old or new?

Old.  We'll cut over to new when we upgrade the mainnet.

**Comment by albertandrejev** [comment]
Should be added to the production config (https://github.com/iov-one/ponferrada/blob/69728c61351f3a1ff5c35f05ac0ce9844a543a3a/packages/bierzo-wallet/src/config/production.json#L13):
* cosmos-binance-chain-tigris
* bip122-tmp-bcash
* tezos-tmp-mainnet

@davepuchyr please confirm.

**Comment by davepuchyr** [comment]
Correct

**Comment by albertandrejev** [comment]
@davepuchyr can you give me proper chain names for those IDs? https://github.com/iov-one/ponferrada/issues/1054#issuecomment-608411783

**Comment by davepuchyr** [comment]
> @davepuchyr can you give me proper chain names for those IDs? [#1054 (comment)](https://github.com/iov-one/ponferrada/issues/1054#issuecomment-608411783)


cosmos-binance-chain-tigris -> Binance Chain
bip122-tmp-bcash -> Bitcoin Cash
tezos-tmp-mainnet -> Tezos
