### ISSUE TITLE
Improvement for block explorer

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1077]
Goal:
It would be nice if a user could enter an IOV address into the explorer and a list of all the transactions associated with the address would appear.  

Examples include https://www.mintscan.io/account/cosmos10vlelfg43tmyem0znppdsetnpud2ml0uhwje7e and https://etherscan.io/address/0x4a8b4961e0889182e4277afbb3f0dd83981670cc.

**Comment by davepuchyr** [comment]
Closed via https://github.com/iov-one/quick-block-explorer-frontend/pull/35
