### ISSUE TITLE
Starname testing

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1080]
On staging environment:
- [x] Register starnames/names
- [x] Register iovnames
- [x] List empty screen
- [x] New transactionsfor account module in wallet
- [x] IOV Core work (add support for listing starnames)
- [x] List starnames/names
- [x] List iovnames
- [x] Manage starnames/names
- [x] Manage iovnames
- [x] Transfer starnames/names
- [x] Transfer iovnames
- [x] Delete starnames/names
- [ ] Delete iovnames
- [x] Renew starnames
- [x] Assign name back to me
- [x] Wallet: Transactions support
- [x] Extension: TX request support

- [x] Check list of starnames/names after transfering it to another user
- [x] Check list of starnames/names after transfering it back from another user
- [x] Check iovname transaction record in the Transactions screen
- [x] Check list of starnames/names after deletion
- [x] Check list of starnames/names after creation

**Comment by albertandrejev** [comment]
I can not understand how starname/name renewal is working. I tried to renew existing starname, but nothing happens. Expiration data was not changed. On staging, Exchangenet 📈

**Comment by albertandrejev** [comment]
List of owned names was not changed runtime after transferring name away from owner and back to owner. It updates only after page reload.

**Comment by albertandrejev** [comment]
@davepuchyr Unable to properly transfer starname to new owner. 
1. It creates "Starname transfer" tx properly
2. Starname transferred to new owner
3. All targets removed from default name
**4. Ownership of the default name did not changed to new owner
5. Ownership of all other names of this starname did not changed to new owner
6. Targets of all other names of this starname did not cleared.**

You can try this on staging.

**Comment by albertandrejev** [comment]
Transfer iovname - "**This is an unknown transaction**" on the wallet Transactions screen.

**Comment by albertandrejev** [comment]
@davepuchyr  Domain renewal still is not working or I do not understand how it should working

**Comment by albertandrejev** [comment]
From time to time new name is not appearing in the list of owned names. Check transaction processing.

**Comment by albertandrejev** [comment]
Transferred starnames/names should be removed from list of owned startnames/names

**Comment by davepuchyr** [comment]
> I can not understand how starname/name renewal is working. I tried to renew existing starname, but nothing happens. Expiration data was not changed. On staging, Exchangenet  @davepuchyr

Great catch! https://github.com/iov-one/weave/issues/1204

**Comment by davepuchyr** [comment]
> @davepuchyr Unable to properly transfer starname to new owner.
> 
> 1. It creates "Starname transfer" tx properly
> 2. Starname transferred to new owner
> 3. All targets removed from default name
> 4. **Ownership of the default name did not changed to new owner**
> 5. **Ownership of all other names of this starname did not changed to new owner**
> 6. **Targets of all other names of this starname did not cleared.**
> 
> You can try this on staging.

The transfer worked perfectly for me.  I'm guessing that you did your test prior to the reboot of `exchangenet`.  Please try again and let me know your results.

**Comment by davepuchyr** [comment]
> @davepuchyr Domain renewal still is not working or I do not understand how it should working

I think that we have some confusion about renewing the domain and renewing the empty name account within the domain.  If I register `*albert` and then manage it and renew it, the domain should be renewed, not the account.  The account will automatically be renewed when https://github.com/iov-one/weave/issues/1204 is implemented.  Does that clarify the situation?

**Comment by albertandrejev** [comment]
Sorry, forgot to mention this. Yes, transfer is working now.

**Comment by albertandrejev** [comment]
> I think that we have some confusion about renewing the domain and renewing the empty name account within the domain. If I register *albert and then manage it and renew it, the domain should be renewed, not the account. The account will automatically be renewed when iov-one/weave#1204 is implemented. Does that clarify the situation?

Yes, thank you.

**Comment by albertandrejev** [comment]
@davepuchyr another interesting issue. Steps to reproduce:
1. Create domain;
2. Create name for this domain;
3. Transfer this name to somebody else;
4. Try to transfer it back, you will get "domain expired" error.

**Comment by albertandrejev** [comment]
@annatorok can not understand what does it means: "Register empty screen"

**Comment by davepuchyr** [comment]
> @davepuchyr another interesting issue. Steps to reproduce:
> 
> 1. Create domain;
> 2. Create name for this domain;
> 3. Transfer this name to somebody else;
> 4. Try to transfer it back, you will get "domain expired" error.

I set the domain renewal period to just 100 seconds while I was testing the operations that are dis/allowed after expiration, so I think that's why the domain is expired in your case.  I'll set it to 24 hours now.

**Comment by abefernan** [comment]
For deleting an iovname we would need a new Tx type on iov-core.
