### ISSUE TITLE
Name Renew is not implemented

### ISSUE THREAD

**Issue by abefernan** [iov-one/ponferrada#1085]
The Renew functionality is implemented for starnames but not for names. (iovnames do not have a renew functionality).

The Name actions options will be removed from name/manage in #1072.

**Comment by albertandrejev** [comment]
There is no name renew (expect iovname) wireframe. Name renewal is based on starname renewal.

**Comment by abefernan** [comment]
Ok, the Manage Name view shows a Renew option that does nothing

**Comment by abefernan** [comment]
> There is no name renew (expect iovname) wireframe. Name renewal is based on starname renewal.

Ok, the Manage Name view shows a Renew option that does nothing

**Comment by albertandrejev** [comment]
Yes, it should be removed.

**Comment by abefernan** [comment]
Concerns compiled in #1093.
