### ISSUE TITLE
Refactor react-hooks/exhaustive-deps

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#143]
Due to the last update of react-scripts now we lint hooks errors. For not blocking development we have silenced some errors.

Please, find `// eslint-disable-next-line react-hooks/exhaustive-deps`  references (specially SelectFieldForm) and refactor it.

**Comment by webmaster128** [comment]
eslint can auto-fix those cases. It just makes every symbol in the `useEffect` body a dependency.

But to be honest, I don't think this linting rule is very useful as at forces you to put all kind of constant variables into the list of dependencies, no matter if your component needs depends on them or not.

**Comment by apanizo** [comment]
I am not really worried about the potential errors we are introducing in the code, the worst case we force components to re-rendered which in a 240KB app is nothing. 

The thing is I want to deeply understand the reasons of those lint rules. React will move into functional components, using hooks as a primary tool, so I need to investigate it. This ticket does not hurt.

**Comment by webmaster128** [comment]
This is in Done on the board
