### ISSUE TITLE
Transaction request flow should be recalculated,  initial suggestion is from the main view

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#155]
https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674184

Just go to "account status view" and show the info (if the tx has been rejected should be in txs space, if approved should be shown in pending txs section)

**Comment by webmaster128** [comment]
huh? This is interesting. As far as I am aware of, rejected signing requests are not kept available as data. So they are lost. Right now I don't see a reason why we should pollute the UI with them.

Instead, I suggest merging the two transaction lists into one, only list accepted transactions and update the rows when their state changes (signed, posted, accepted by node, in block, number of confirmations). This would simplify all the things as we only have one transactioons data source.

**Comment by kmw101** [comment]
Let keep things simple in that case.

**Comment by kmw101** [comment]
Done
