### ISSUE TITLE
Website request (getIdentities or signAndPost) with a reason

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#168]
We have a `reason` string available to explain the user _why_ they should accept the request as a form of _data receiver -> user communication_, a form of building trust.

This is displayed in the balance and transaction request views.

**Comment by webmaster128** [comment]
The `reason` string as defined by the website is available in the callbacks

```ts
        const getIdentitiesCallback: GetIdentitiesAuthorization = async (
          _reason,
          matchingIdentities
        ): Promise<ReadonlyArray<PublicIdentity>> => {
```

and 

```ts
        const signAndPostCallback: SignAndPostAuthorization = async (
          _reason,
          _transaction
        ): Promise<boolean> => {
```

and should be shown in the UI from there.

**Comment by webmaster128** [comment]
Closing since this is done
