### ISSUE TITLE
Chrome extension visual improvements

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#198]
In case this ticket applies, we should split those tasks in different tickets.

We should apply those changes for more consistency:

- [ ] Background by default should be white, and static views like, welcome or signup can only have grey background. For achieving that, we should update PageLayout (now by default it has a transparent background and has a white one as optional).
- [ ] If the view, for whatever reason is smaller than the default box, the IOV icon should stay at the bottom, not shrink with the content.
- [ ] Improve drawer view, make it more beautiful (use icons? Talk to @apanizo and @kmw101)
- [ ] Improve request list view, make it more beautiful ((use icons? Talk to @apanizo and @kmw101)

**Comment by webmaster128** [comment]
Closing since this is was moved into the Archive of the board, so I guess it is outdated.
