### ISSUE TITLE
e2e test bierzo-wallet extension's badge icon

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#204]
This test should create an e2e test checking if the user in bierzo wallet sends a couple of requests for getting identities, the badge text in the extension is updated correctly.

**NOTE**
For implementing this ticket we should assure chrome global is accessible from puppeteer.

**Comment by albertandrejev** [comment]
@apanizo unfortunately I did not find any suitable way to tests the badge text value from wallet other than adding helper method to the extension to call `chrome.browserAction.getBadgeText` method and get answer from it.

**Comment by albertandrejev** [comment]
@apanizo also I found this. Hope this can be helpful too https://github.com/GoogleChrome/puppeteer/blob/v1.16.0/docs/api.md#working-with-chrome-extensions
