### ISSUE TITLE
Toast forwardRef error

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#211]
We are facing this error when using the ToastProvider in our apps:
![Screenshot 2019-05-22 10 55 05](https://user-images.githubusercontent.com/4266059/58161485-9e990f80-7c80-11e9-8b57-ba550390ef42.png)

You can reproduce it easily clicking on "Send request to be signed" in `bierzo-wallet`

We need to update our Toast implementation and use `forwardRef`. Some links for reference:
- https://reactjs.org/docs/forwarding-refs.html
- https://github.com/atomiks/tippy.js-react#component-children

**Comment by albertandrejev** [comment]
I already have solution for this issue, it was implement in early versions of Toast component. But was overwritten after.
