### ISSUE TITLE
Exception raised in bierzo-wallet when reject request

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#212]
In bierzo-wallet webapp, if you reject a `getIdentities` request you see an exception in console, this should not happen, just send a toast message.

The code should be defensive covering the response without raising the error.

![Screenshot 2019-05-22 11 03 43](https://user-images.githubusercontent.com/4266059/58161931-7d84ee80-7c81-11e9-831e-548ca4100fc9.png)

**Comment by webmaster128** [comment]
@albertandrejev the core of this error message is the following: In https://github.com/iov-one/ponferrada/blob/c344cb4ec4343a69f8de8cee3756796c3858f7a6/packages/bierzo-wallet/src/routes/welcome/index.tsx#L40-L41, `sendGetIdentitiesRequest` succeeds but the user decided to reveal 0 identities (that is what happens on reject), so `identities` is an emty list. Now `identities[0]` is used even if the list is empts (missing length check). When trying to encode `identities[0]`, which is `undefined` in line 41, the above error message is created.

**Comment by albertandrejev** [comment]
But this happens on `accept` too.
