### ISSUE TITLE
Restore Account Part II

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#22]
As a user I am shown a screen which asks me to enter my password. I am also shown a password hint.

I have a back button to take me to the Restore Account Part I page.

The continue button is inactive until I have entered something into the password input box.

~I also have an option to reset my password with a link labelled "reset password"~

If I enter the wrong password, I am shown an error toaster "you have entered an incorrect password". 

If I enter the correct password then I am taken to the account status page. 

https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/341373579

**Comment by albertandrejev** [comment]
I think you should be redirected to this page after clicking on "Restore account" at https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674175. And only then you can choose "Restore by security phrase" or "reset password" in case if can not recall your password using security phrase. And after clicking on this link you will be redirected to https://github.com/iov-one/ponferrada/issues/21

Something like this:
Login page restore account -> Restore by hint -> Restore by security phrase.
I am not 100% sure about this flow. But I think I passed the idea.

**Comment by albertandrejev** [comment]
As far as I understand this system should be multi user, so we need to provide user name before to get hint phrase for this user.

**Comment by kmw101** [comment]
> I think you should be redirected to this page after clicking on "Restore account" at https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674175. And only then you can choose "Restore by security phrase" or "reset password" in case if can not recall your password using security phrase. And after clicking on this link you will be redirected to #21
> 
> Something like this:
> Login page restore account -> Restore by hint -> Restore by security phrase.
> I am not 100% sure about this flow. But I think I passed the idea.

Let's keep this simple and show the security hint at the login page if the user enters the wrong password.

So I get a message "Password incorrect - hint: 'What is the name of your best friend at your first school?'"

Keep the part II to change the password, and add an input to update the security hint.
