### ISSUE TITLE
Auto height size to extension

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#235]
Sometimes when one dynamic view in the extension is higher than the extension' size, the layout container does not fit the entire screen.
See: 
![Screenshot 2019-05-29 15 34 40](https://user-images.githubusercontent.com/4266059/58562183-0cb57780-8229-11e9-9471-4d6affa85cd9.png)

It seems: 
```
height: "auto"
 minHeight: "100vh" 
```
solve the problem. Check it out.

Also, if the screen is too small, the IOV icon shrinks to the panel. See:
![Screenshot 2019-05-29 15 48 21](https://user-images.githubusercontent.com/4266059/58562277-3a022580-8229-11e9-9cf1-9a85df0e5b4c.png)
And it should stay at the bottom of the window.

**Comment by apanizo** [comment]
Once this is solved, please, update tx-request ShowRequest.tsx and use:
`<PageLayout ... color="white" ...>`

See:
![Screenshot 2019-05-30 11 50 14](https://user-images.githubusercontent.com/4266059/58625180-2f4f9b00-82d2-11e9-8f5d-1f170901f317.png)

**Comment by abefernan** [comment]
> Once this is solved, please, update tx-request ShowRequest.tsx and use:
> `<PageLayout ... color="white" ...>`
> 
> See:
> ![Screenshot 2019-05-30 11 50 14](https://user-images.githubusercontent.com/4266059/58625180-2f4f9b00-82d2-11e9-8f5d-1f170901f317.png)

Once the height issues have been addressed in #243:
- Share Identity's accept/reject dialog is grey.
- Share Identity's reject confirmation dialog is grey.
- TX Request's accept/reject dialog is grey.
- TX Request's reject confirmation dialog is white.

So, which color should be each view?

**Comment by apanizo** [comment]
white!
