### ISSUE TITLE
Login route UI

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#247]
The account management logic is now in the extension. The demo wallet log-in page needs to be changed as follows:
- [x] Update redux store with extension state support (PR #272);
- [x] Remove the “Don’t have an IOV wallet” text and hyperlink;
- [x] Remove the Password text and input box.Remove the “Forgotten password” link;

**Comment by kmw101** [comment]
Correct if the account is logged in then go to the /balance page.

**Comment by albertandrejev** [comment]
@apanizo is there any way to check extension status: not logged in, profile doesn'tt exists.

**Comment by albertandrejev** [comment]
I mean is there direct way or this is only possible by analysing behaviour of the extension's answers on `sendMessage` request?

**Comment by apanizo** [comment]
So far the only option is to analyse the extension's answers. But we can open a feature request on the extension, besides `getIdentities` and `signAndPost` a third one like `status` for knowing on which state persona is.

@kmw101 can you give a thought and schedule it for after MVP?

**Comment by kmw101** [comment]
`status` would imply a number of possible `states`. Would a simple `is_connected` be better? 

Agree, should come after MvP.

**Comment by albertandrejev** [comment]
Yes, there is at least two possible `states` I can imagine: logged in, profile created. What else?

**Comment by kmw101** [comment]
Thanks, I will add an issue to the extension and once that is done raise an issue here.

**Comment by kmw101** [comment]
Following the discussion this morning I have amended the issue description.
