### ISSUE TITLE
Balance Page : Request ID and then query node

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#250]
Request the identity from the extension and then in the balance page query the node directly (we had a PR where we removed this functionality from the extension, you can take a look there and also in wallet-demo).

**Comment by albertandrejev** [comment]
This should be already done. @apanizo

**Comment by apanizo** [comment]
Yes! In fact, in my last PR I have even implemented the account's balances subscription for the received identities from the wallet. It should work out of the box right now.

**Comment by webmaster128** [comment]
Done, thanks
