### ISSUE TITLE
Remove Security Centre 

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#254]
The security centre used in the demo wallet is not needed, please remove.

**Comment by webmaster128** [comment]
With this change in place, the user can easily register multiple names (by shopping multiple times). I think this is okay but something we need to consider in the rest of the UI as well. Over time, some multi-address management functionality needs to be created (names overview page, update names, transfer names).

**Comment by kmw101** [comment]
> With this change in place, the user can easily register multiple names (by shopping multiple times). I think this is okay but something we need to consider in the rest of the UI as well. Over time, some multi-address management functionality needs to be created (names overview page, update names, transfer names).

The original intent was to have somewhere where a user could buy a name. That functionality has been included in the balance page, and the registration menu item is not needed for MvP. The multiple personalised address is a good proposal but not for MvP.

**Comment by webmaster128** [comment]
Agreed. Given that nothing is left from the security center now, we can change this ticket to "Remove security center", right?

The shop idea can follow later.

**Comment by kmw101** [comment]
> Agreed. Given that nothing is left from the security center now, we can change this ticket to "Remove security center", right?
> 
> The shop idea can follow later.

I have updated the title and description.
