### ISSUE TITLE
List of proposals: implement sorting based on menu selection

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#282]
After https://github.com/iov-one/ponferrada/issues/281 is implemented, the list of proposals should be filtered depending on the selected main menu item.

As a user I can sort the column on:

* Expiration date
* Creation date
* Vote [ yes/no/abstain ]

https://www.figma.com/file/ffb3NsuSizFxKzwApMxewRgN/Voting?node-id=0%3A1

**Comment by webmaster128** [comment]
This is a problem once there is a significant number of proposals. -> later
