### ISSUE TITLE
Logic proposal for voting

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#283]
Request the list of proposals from the extension.

Each proposal has the information shown about the proposal:

* Title
* Description
* Expiry date
* Creation date
* Quorum
* Threshold

There is a second column for voting with 3 buttons

* Yes
* No 
* Abstain

If the user has voted the button is highlighted:

https://app.zeplin.io/project/5cb65f5c34967632b48fcb12/screen/5cb65f7d50961164eea4925a

**Comment by webmaster128** [comment]
> Request the list of proposals from the extension.

This is a misconception. The only purpose of the extension is to provide user identities and sign transactions. Instead, the flow is as follows:

1. Voting app requests identities for chain ID `local-bns-devnet` from the extension
2. From that list, the user needs to pick one identity. We can create a shortcut here and always use the first one
3. Voting app establishes a connection to BNS
4. The @iov/bns-governance package will provide a nice helper, giving you the list of proposals from the BNS connection (3.) and the identity (2.)

**Comment by webmaster128** [comment]
Almost done and superseded by more specific tickets now
