### ISSUE TITLE
Block Requests from websites

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#29]
Each time a website makes a request to the browser extension the website is checked against the list of blocked websites. If it is on the list then the request is ignored, if it is not on the list then the request is shown.

Example
---------
Blocked website list
foo.io
bar.co

Scenarios
I visit foo.io and it requests permission to see my ETH balance, request rejected
I visit acme.one and it requests permission to see my ETH balance, request sent to browser extension

**Comment by apanizo** [comment]
Blocked by #156

**Comment by webmaster128** [comment]
Closing as done
