### ISSUE TITLE
Proposal Types

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#302]
The election types are documented in the code:

[Elections - Sheet1.pdf](https://github.com/iov-one/ponferrada/files/3277476/Elections.-.Sheet1.pdf)

**Comment by webmaster128** [comment]
We are working on a @bns-governance package that will make those types available in a very convenient fashion: https://github.com/iov-one/iov-core/pull/1109

**Comment by webmaster128** [comment]
Done in @iov/bns-governance. Follow up with more specific tickets
