### ISSUE TITLE
Introduce tickers in store

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#336]
- [x] Added harcoded tokens to store
- [x] Include chains config in project
- [x] Inject properly available tokens

This ticket will introduce all tickers from supported chains inside redux, for making the information available in the app (especially balance and send payment route).

The structure will follow:
```
{  tickers: 
      "BOV": {
           chainId: '...'
           ticker: { fractionalDigits, tokenTicker, tokenName}
     }
     ....
} 
```

**Comment by webmaster128** [comment]
Closing since done
