### ISSUE TITLE
Add T&C links

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#342]
The Browser Extension needs to have terms and conditions of use. 

Please add a link to the account status page to 

https://support.iov.one/hc/en-us

With the text Terms and Conditions of use.

**Comment by davepuchyr** [comment]
> The Browser Extension needs to have terms and conditions of use.
> 
> Please add a link to the account status page to
> 
> https://support.iov.one/hc/en-us

This is not the correct link.  You can use it as a placeholder for now, but expect to change it with a direct link to Terms & Conditions when I can provide it.
> 
> With the text Terms and Conditions of use.

**Comment by albertandrejev** [comment]
Yes of course, just let me know.

**Comment by webmaster128** [comment]
Can we hide that link a little bit (e.g. in the bottom of the drawer that opens with the hamburger menu)? In the main view of the extensions it looks a bit annoying.

**Comment by kmw101** [comment]
That is what I was thinking, an icon with a link in the hamburger menu. Can this be done @albertandrejev ?

**Comment by albertandrejev** [comment]
Yes I think so.
