### ISSUE TITLE
Implement MsgRegisterUsernameTx React component

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#344]
We now have multiple transaction types and need one component per type.

A stub MsgRegisterUsernameTx already exists. It needs to be updated to display all the important data of the transaction.

**Comment by albertandrejev** [comment]
@kmw101  do we have any mock-ups for this component?

**Comment by webmaster128** [comment]
Done in https://github.com/iov-one/ponferrada/pull/361
