### ISSUE TITLE
Implement ReqRegisterUsernameTx React component

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#349]
We now have multiple transaction types and need one component per type. 

A stub ReqRegisterUsernameTx already exists. It needs to be updated to display all the important data of the transaction.

**Comment by albertandrejev** [comment]
@kmw101  do we have any mock-ups for this component?

**Comment by kmw101** [comment]
We don't have one. Do you need guidance?

**Comment by albertandrejev** [comment]
I think I do not need any. Thank you.

**Comment by albertandrejev** [comment]
@webmaster128 can you tell me what is the difference between this ticket and https://github.com/iov-one/ponferrada/issues/344

**Comment by webmaster128** [comment]
> can you tell me what is the difference between this ticket and #344?

there are two places whete transactins are displayed:
1. Before the transaction is signed, in the signing request (ReqRegisterUsernameTx)
2. After the transaction was signed in the list of transactions (MsgRegisterUsernameTx)

It would be good to have only one component per transaction type for both 1. and 2. But right now I think it is easier to stick with the current structure and deduplicate later.

The information what should be displayed is (sketch):

> Register { username }*iov with addresses { bnsAddress } ({ bnsChainName }),  { ethereumAddress } ({ ethereumChainName }), { liskAddress } ({ liskChainName }).
> Fee: { fee }

**Comment by albertandrejev** [comment]
> 2. After the transaction was signed in the list of transactions (MsgRegisterUsernameTx)

Are you talking about "Account Status/Transactions" list?

**Comment by webmaster128** [comment]
exactly

**Comment by albertandrejev** [comment]
Also are you sure that it is required to show chains during name registration request? Because as far as I understand when additional chains will be added then they will be associated with name automatically (during next session). So this is not very helpful to show this metadata.

**Comment by webmaster128** [comment]
> Also are you sure that it is required to show chains during name registration request?

For the wallet-demo-like use case, one could argue that this could be hidden from the user. However taking aways the signing step from the wallet app is a strong security guarantee: The wallet app can generate any kind of transaction, when there is some kind of hack. Showing the user in the extension exactly what is signed with all the information that belong to the transaction guarantees that the user has a chance to verify if that is what they want to sign. Thus we should make it a habit to show all the data that is included in a transaction.

> then they will be associated with name automatically (during next session)

Adding a new address to a username cannot be fully automatic in a production system since the user needs to pay fees for every `AddAddressToUsernameTx`. So we 1. need to let the user choose if they are willing to pay that fee and 2. when the user creates a new account, they will not have IOV tokens available before someone sends them tokens to their new BNS address.

**Comment by albertandrejev** [comment]
Thank you for the explanation

**Comment by albertandrejev** [comment]
@webmaster128 how to prepare and send request from `bierzo-wallet` to extension with name creation request?

**Comment by webmaster128** [comment]
Combine
1. Transaction creation and sending to extension as in https://github.com/iov-one/ponferrada/blob/f1c1c66/packages/bierzo-wallet/src/communication/signAndPost/index.ts#L16-L35
2. Creation of a `RegisterUsernameTx` instead of a `SendTransaction` https://github.com/iov-one/iov-core/blob/v0.14.5/packages/iov-bns/src/bnsconnection.spec.ts#L657-L662

The `username` is the IOV address without the `*iov` suffix.

In the most simple case, only one address is added (the user's BNS address), which you get from `bnsCodec.identityToAddress(identity)`. The chain ID is available in `identity.chainId`.

**Comment by albertandrejev** [comment]
Also I need sample request data to show for `tx-request/index.stories.tsx`.

**Comment by albertandrejev** [comment]
No need for sample request, I think I found it by myself.
