### ISSUE TITLE
Add a proposal screen

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#372]
As a user I want to add a new proposal. Not not all proposals are the same, there are different inputs for each proposal.

There are the following proposal types.

- [ ] Add a validator
- [ ] Remove a validator
- [ ] add a committee member
- [ ] remove a committee member
- [ ] amend the vote threshold 
- [ ] amend the quorum
- [ ] move funds from guarantee to reward account
- [ ] distribution of funds
- [ ] amend blockchain software

Detailed description of the proposals and their inputs are in the following file.
[Governance_  Proposals.pdf](https://github.com/iov-one/ponferrada/files/3373751/Governance_.Proposals.pdf)

UX guideline
https://www.figma.com/file/ffb3NsuSizFxKzwApMxewRgN/Voting?node-id=0%3A1

**Comment by webmaster128** [comment]
Superseded by more specific tickets
