### ISSUE TITLE
Feature #302 - Adapt Proposal types on Frontend

### ISSUE THREAD

**Issue by abefernan** [iov-one/ponferrada#437]
**Description**

Adapts the Frontend `ProposalProps` type for rendering Proposals so its types better match those of IOV Core BNS `Proposal`'s.

Adapts the layout to acomodate the new types and to comply with the new wireframes present at [Figma](https://www.figma.com/file/ffb3NsuSizFxKzwApMxewRgN/Voting?node-id=0%3A1).

Part of #302.

**Comment by webmaster128** [comment]
Done in #302
