### ISSUE TITLE
Fix error messages when sending to personalized address

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#450]
I registered the username

```
[ { id: 'simon*iov',
    owner: 'tiov15auuk2w3nut5s680px7tfr6ukfyn8t7ypakvx3',
    targets: [] } ]
```

i.e. a username with no connected addresses. When I try to send to this personalized name, the current error message is misleading. What we want is:

1. If username does not exist: "Recipient's personalized address was not found"
2. If no address was registered for the chain ID: "Recipient's personalized address does not contain an address for this blockchain"

**Comment by albertandrejev** [comment]
What do you think is better, to use field validation to check or validate on submit and show error using toast?

**Comment by webmaster128** [comment]
I think we should keep field validation for the quick, synchonous, offline format checks and test the rest after submit only. This saves many requests to the blockchain and is roughly what the user would expect.
