### ISSUE TITLE
Improve Chrome extension requests flow

### ISSUE THREAD

**Issue by willclarktech** [iov-one/ponferrada#523]
When the website makes a request, the extension shows a little badge (so far so good). Then when you open the extension there’s no guidance about where to go next, you just have to know/remember/guess you have to click on the menu and navigate to “requests”.

Possible improvements:
- take the user to that page directly when the extension is opened and requests are pending
- highlight the path to that page a bit more clearly e.g with more badges on the menu icon/requests item
- have a popup that puts the request queue above the rest of the UI
- add a requests view to the homepage

**Comment by kmw101** [comment]
My vote is to open the page with the pending requests.

**Comment by apanizo** [comment]
@kmw101 I think it is a good idea what you say.

@webmaster128 ? Can you confirm Martin's proposal is what we want?

**Comment by webmaster128** [comment]
@apanizo 👍 confirmed. This is a staight forward approch that avoid the necessarity to create new screens. It is easy to implement and does not require a big design process.
