### ISSUE TITLE
Wallet menu items

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#530]
From the drop down menu <Hi!>

There are links to 
* ~Invite Friends~
- [x] Terms and Conditions (PR #554)
- [ ] Privacy Policy (PR #563)

Copy the pages from the demo wallet and link them to the menu.

**Comment by webmaster128** [comment]
Feedback from UI team was to remove "Invite Friends" as well. I'm removing it from this ticket for now and extract onto separate ticket: https://github.com/iov-one/ponferrada/issues/540 At the moment, I don't see an "Invite Friends" functionality as part of MVP. Feel free to disagree.

**Comment by kmw101** [comment]
> Feedback from UI team was to remove "Invite Friends" as well. I'm removing it from this ticket for now and extract onto separate ticket: #540 At the moment, I don't see an "Invite Friends" functionality as part of MVP. Feel free to disagree.

I also commented on #540 - seeing as this is existing functionality in the demo wallet should be easy to port to the bierzo wallet?
