### ISSUE TITLE
Review Invite Friends page

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#540]
In wallet demo we has the following page:

![Screenshot_2019-08-19 Iov Demo App](https://user-images.githubusercontent.com/2603011/63298296-6f238e80-c2d3-11e9-8cfa-fa34436cb92a.png)

via

<img width="779" alt="Bildschirmfoto 2019-08-19 um 22 49 46" src="https://user-images.githubusercontent.com/2603011/63298417-b3af2a00-c2d3-11e9-95da-26f1a0546abf.png">

Is this something we still want? If yes, please refine referral program or update wording.

**Comment by kmw101** [comment]
As this is existing functionality in the demo wallet is it really that hard to migrate? The wording does not need to change.

**Comment by webmaster128** [comment]
I agree the page is trivial to copy, since it is basically static content.

However, there is no such thing as a referral system designed. The page sugegsts there is a personalized link that does something for the current user when used to invite someone else. Additionally, the homepage link shown there (iov.one) does not point to the product but to the company website of IOV SAS. Since I am not aware of any product-specific landing page, I don't have an alternative link to use here.

We can have a page like this in the future, but what I'm seeing right now is too inconsistent to copy into the fresh wallet app.

**Comment by kmw101** [comment]
The original design and concept dated from Nov 2018 so probably good to archive unless someone comes up with a plan.

**Comment by kmw101** [comment]
Not a requirement.

**Comment by webmaster128** [comment]
Agreed. +1 for closing
