### ISSUE TITLE
Make sure electorates + election rules are enough for testing

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#561]

**Comment by willclarktech** [comment]
This should be covered by https://github.com/iov-one/ponferrada/pull/555
We may need to add more as/when necessary though. @abefernan Good to close this issue?

**Comment by abefernan** [comment]
> 
> 
> This should be covered by #555
> We may need to add more as/when necessary though. @abefernan Good to close this issue?

Yes, I believe it can be closed.
