### ISSUE TITLE
Create confirmation step when deleting wallet

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#565]
After https://github.com/iov-one/ponferrada/issues/564

-------

Right now, one misclick on the delete wallet button can cost you all your tokens. An additional confirmation step should be in place in the code at

```ts
      action: async () => {
        // TODO: Ask for confirmation
        try {
          await clearPersona();
          await clearDatabase();
        } catch (error) {
```

I din't know how an UI for this could look like. Ideas?

**Comment by albertandrejev** [comment]
I think UI should contain input and user should tell explicitly that he wants to delete wallet. Something like:
"Are you sure want to completely delete this wallet? Please time 'Delete wallet' in field below."
&lt;Input field&gt;

**Comment by webmaster128** [comment]
You could even go wone step further and require to type in the mnemonic, which somehow ensures that the use still have it after removing the wallet. cc @kmw101 any thoughts on this ticket?

**Comment by kmw101** [comment]
I have no idea where this requirement came from.

It would be sensible to enter the mnemonics in to make sure you don't accidentally delete the wallet.

**Comment by webmaster128** [comment]
The source of the requirement is a developer who realized that when you by accident click the "Logout" (soon called "Remove wallet") button, all data is erased. It was first mentioned in a source code comment "// TODO: Ask for confirmation" months ago and was converted to a ticket now for visibility.

**Comment by kmw101** [comment]
In that case there are two paths:

1) Ensure that during the "logout" process the data is not erased, just the session terminated requiring login to resume service.

2) Require the mnemonic to be entered before deleting everything.

**Comment by webmaster128** [comment]
In case of 1. there would be absolutely no way to use different mnemonics. It would change "Remove wallet" to "Lock" (which is a feature [scheduled for later](https://github.com/iov-one/ponferrada/issues/178)). So I prefer 2.

**Comment by albertandrejev** [comment]
I think asking user to enter wallet's mnemonic in order to remove it is good idea. I will implement it in this way.

**Comment by albertandrejev** [comment]
Confirmation text - "Are you sure want to completely delete this wallet? Please type current wallet recovery phrase in field below.". Any suggestions?

**Comment by kmw101** [comment]
Looks good to me.
