### ISSUE TITLE
Remove sentry

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#574]
As long as we have no GDPR-complient UX, we should remove all traces of sentry from the codebase.

This incluses the package `@sentry/browser` as well as all usages of it. The `ErrorBoundary` component is good to keep. But whatever is cought should be logged to `console.error` instead of being sent to an external service.

**Comment by albertandrejev** [comment]
There is no need to left `ErrorBoundary` at all. Because this is default React behaviour to show error on the console.

**Comment by webmaster128** [comment]
@albertandrejev please choose the solution you find most convenient to implement. My idea was that we might re-introduce sentry once we have the requirement and UX/GDPR specifications. Possibly this will never happen. So feel free to cleanup what is not needed now.
