### ISSUE TITLE
Create Signup Page Part I

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/ponferrada#6]
https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674197

**STEPS**
- ~~[ ] PR 1: Add Carousel component to `medulas-react-components` creating storybook story for doing it~~
- [x] PR 2: Add react-final-form to sanes-chrome-extension, and use it using the hooks mode. (#47)
- [x] PR 3: Include TextField in medulas-react-components and use it inside the form (#48)
- [x] PR 4: Create layout of `routes/signup` in chrome extension
- [x] PR 5:  Introduce logic (what happens when you click on "Continue") for creating account

**Comment by webmaster128** [comment]
Closing since this is done
