### ISSUE TITLE
Show hint when user interaction in extension is required

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#606]
When a `getIdentities` or `signAndPost` request is sent, it is not clear to users that they need to interact with the extension in order to continue.

Can we print a hint like "Please authorize in NEUMA" (the new name of the extension)? Ideally this should be written into the button that was triggering the event. But this is probably too long. Can we still give it a try? Other ideas?

**Comment by albertandrejev** [comment]
What about hiding UI by semitransparent panel blocking all controls on the wallet with hint text on it?

**Comment by webmaster128** [comment]
Sounds good. Seems to be easy to implement in the same way for all types of authorization requests.

**Comment by albertandrejev** [comment]
Yes, I will add additional `Context` like `Toast` and it can be called anytime.

**Comment by webmaster128** [comment]
I like the approch, especially since it allows for more explanation text (later) and maybe even some visial elements.
