### ISSUE TITLE
Add NEUMA logo

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#613]
Now that the browser extension gets its own identity (NEUMA), we need to replace the IOV logo with a NEUMA logo.

Blocked since logo was not yet provided.

**Comment by davepuchyr** [comment]
This isn't the final version but will suffice for now.  [Neuma_Concept1_.zip](https://github.com/iov-one/ponferrada/files/3565798/Neuma_Concept1_.zip)
