### ISSUE TITLE
Create web app example

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#66]
For interacting with the extension we need an example web app.

This project should live inside ponferrada monorepo, and should be called `bierzo-wallet`.

Steps:
1. Create repo using create-react-app typescript version inside packages
2. Load medulas-react-components using `lerna add` medulas dependency
3. Find an inspiration BASIC webpage with BASIC functionality:
    - Requesting access to website
    - Send tx o IOV address

Keep in mind the web app should manage negativa answers from the extension (the extension rejects your petition, the extension fails when sending the tx)

**Comment by kmw101** [comment]
Looking at the Demo Wallet, there is only the send transaction that needs signing. Please use the Demo Wallet as the web application to interact with the browser.

There are a number of flows in the [document ](https://docs.google.com/presentation/d/1a8QjPozeix_XUiufs2CCYWfYvdRSLH0G2PGbKOxFz8w/edit#slide=id.p)which show how the send token works with the signer.

**Comment by kmw101** [comment]
Following a Slack conversion this is not a requirement.

**Comment by webmaster128** [comment]
Closing as this is done
