### ISSUE TITLE
Error in casting a vote: vote time before start date

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#676]
I vote on a proposal, sign with the extension and I stay on the screen:

![image](https://user-images.githubusercontent.com/30301533/64411712-bfe20800-d085-11e9-9deb-b4c14419552d.png)

On opening the browser console I see the following 

`Uncaught (in promise) Error: {
  "data": {},
  "log": "cannot check tx: vote before proposal start time: invalid state",
  "code": 10,
  "hash": {
    "0": 61,
    "1": 71,
    "2": 116,
    "3": 217,
    "4": 211,
    "5": 64,
    "6": 5,
    "7": 254,
    "8": 82,
    "9": 62,
    "10": 189,
    "11": 9,
    "12": 109,
    "13": 70,
    "14": 23,
    "15": 227,
    "16": 196,
    "17": 184,
    "18": 168,
    "19": 22,
    "20": 39,
    "21": 173,
    "22": 230,
    "23": 233,
    "24": 154,
    "25": 250,
    "26": 204,
    "27": 116,
    "28": 183,
    "29": 128,
    "30": 10,
    "31": 196
  }
}'

The error message should be reported on the screen OR don't allow the user to vote?

**Comment by kmw101** [comment]
While the error message "vote before proposal start time" is useful, it would be beneficiary to fix the underlying cause.
Re-opening the issue.

**Comment by webmaster128** [comment]
Replaced by https://github.com/iov-one/ponferrada/issues/723
