### ISSUE TITLE
Inconsistency of terms: "recovery words", "recovery phrase".

### ISSUE THREAD

**Issue by albertandrejev** [iov-one/ponferrada#687]
There is different terms used in extension on wallet restoration screen. 

![Снимок экрана от 2019-09-09 10-27-39](https://user-images.githubusercontent.com/3502260/64511578-4e0bf780-d2ed-11e9-9869-1b2fdc580d8c.png)

**Comment by albertandrejev** [comment]
What term should we use?

**Comment by webmaster128** [comment]
@antoineherzog @kmw101 any opinions how we should call those 12 words? Options are

1. recovery words
2. recovery phrase (used by status.im)
3. mnemonic (used in address generator)
4. seed phrase (used by MetaMask)
5. ...

**Comment by kmw101** [comment]
My vote is **recovery words**

5 recovery seed (Trezor)

**Comment by antoineherzog** [comment]
My vote is **recovery words** for me as well.

**Comment by webmaster128** [comment]
I don't mind. Let's go for it
