### ISSUE TITLE
Create proper vote to text helper

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#732]
Given a `vote: VoteOption | undefined`, we should diplay "Yes", "No", "Abstain", "none", implemented by a nice solid helper function.

Right now we have a buggy display for some states

<img width="333" alt="Bildschirmfoto 2019-09-16 um 19 00 07" src="https://user-images.githubusercontent.com/2603011/64977940-a8d8bc80-d8b4-11e9-9f99-d132f5850f91.png">

**Comment by albertandrejev** [comment]
It would be great to put this function into `ui-logic` package.
