### ISSUE TITLE
Vote not counting

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#735]
I enter a proposal, sign it, vote, sign it, wait for the election to end and it shows 0 votes in the dashboard.

![image](https://user-images.githubusercontent.com/30301533/65026139-dd3d8e80-d92f-11e9-8905-57235c15ea87.png)

The browser extension shows the transactions:

![image](https://user-images.githubusercontent.com/30301533/65026227-052cf200-d930-11e9-8065-0e533266dc55.png)

I would expect the dashboard to show the vote I made, and not zero votes.

**Comment by webmaster128** [comment]
Vote value 0 is an internal representation of _Yes_. This is done in https://github.com/iov-one/ponferrada/pull/734. I will deploy it now.
