### ISSUE TITLE
Test if chrome extension can be detected for Wallet users

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#756]
Goal:
Wallet users will need to have the Neuma chrome extension installed on their computers in order to use the wallet. Right now, we don't know if the chrome extension is installed or if the user is even aware that the extension is needed, so to make them aware, we should find a way to explicitly tell them that they need the extension.

Question:
Can we detect if the user doesn't have a chrome extension installed in their browser? Then if they don't, display an install link or redirect the user?

Scope:
To confirm if this is possible or not.

**Comment by webmaster128** [comment]
In order to test this reliably without creating a request in the extension, we need to send a broken `JsonRpcRequest` to the extension. Sending `{}` should do the job. Any reponse other than `undefined` means the extension is installed. `undefined` means not installed.

**Comment by albertandrejev** [comment]
We already have this functionality in our wallet. It can detect extensions status and show message (Toast) in case if application not installed, we change this behaviour and show more detailed message about extension installation.

**Comment by albertandrejev** [comment]
* https://github.com/iov-one/ponferrada/blob/c7843fd61400723515c52082f8097e13f1d58056/packages/bierzo-wallet/src/routes/login/index.tsx#L66
* https://github.com/iov-one/ponferrada/blob/c7843fd61400723515c52082f8097e13f1d58056/packages/bierzo-wallet/src/communication/extension.ts#L28
* https://github.com/iov-one/ponferrada/blob/c7843fd61400723515c52082f8097e13f1d58056/packages/bierzo-wallet/src/communication/extensionRpcEndpoint.ts#L49

**Comment by webmaster128** [comment]
The difference between what we already have and what I described in https://github.com/iov-one/ponferrada/issues/756#issuecomment-534661309 is that what we have will trigger a getIdentities request, which is not desired if the `installed` state should be queried when the user just looks at the wallet front page.

**Comment by albertandrejev** [comment]
Yes, right, I answered to the question in the issue description, about is this possible or not. So yes, this is possible.
