### ISSUE TITLE
Disallow empty recipients file for Distribute Funds

### ISSUE THREAD

**Issue by abefernan** [iov-one/ponferrada#787]
When uploading an incorrect file, it allows the creation of the proposal and sets de recipients to an empty array.

- [x] It should not allow the creation of the proposal (done in #796)
- [x] Show proper error message in UI

**Comment by webmaster128** [comment]
IOV-Core should throw in the `buildCreateProposalTx` call if this case happens: https://github.com/iov-one/iov-core/issues/1276

**Comment by webmaster128** [comment]
When #796 is merged, an empty recipients list results in an error message.

<img width="1053" alt="Bildschirmfoto 2019-10-01 um 14 41 24" src="https://user-images.githubusercontent.com/2603011/65963194-83be7f00-e45a-11e9-806e-a1ddb1ba7672.png">

Even if this message is not perfect, it covers the main issue here, which the creation of proposals with an empty recipients list.
