### ISSUE TITLE
Addresses screen modifications

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#793]
Changes:

- [x] Two new listing section: "Your starnames" and "Your blockchain addresses". At the starnames section, only the starnames will be listed with the corresponding blockchain addresses. If the user doesn't have a starname yet, only blockchain addresses, those will be listed at the "Your blockchain addresses" section. 
- [x] If user doesn't have a starname yet, display the address page registration banner as seen in the design.
- [x] "Return to balance" - button should be removed as seen in the design
- [x] If the user clicks on the copy icon next to a Starname, the addresses should be copied to the clipboard
- [ ] Multiple starnames are listed as seen in the design

Quesions:
- [x] Add design for multiple starname addresses
- [x] Capitalization - can we have consistency?

Steps:
- [x] Modify addresses screen
- [x] Add tab switch
- [ ] Add starname addresses screen

<img width="1440" alt="Demo Wallet - Address tab - Not registered address" src="https://user-images.githubusercontent.com/7419692/66117657-5a762e00-e5d5-11e9-8e1b-28d6a0c97e72.png">

<img width="1440" alt="Demo Wallet - Address tab - Registered address" src="https://user-images.githubusercontent.com/7419692/66117660-5c3ff180-e5d5-11e9-8af7-216e33c82a41.png">

<img width="1440" alt="Demo Wallet - Address tab - Blockchain addresses -Registered address" src="https://user-images.githubusercontent.com/7419692/66117667-5ea24b80-e5d5-11e9-921e-5f0b7c4953cb.png">

**Comment by annatorok** [comment]
Answers:
- multiple starname design added
- now we have consistency with names: starname is always with small s and we don't capitalize blockchain either

**Comment by albertandrejev** [comment]
Unable to fully implement Starnames support. Will be implemented in #849.
