### ISSUE TITLE
Transactions screen modifications

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#794]
Changes:

- [x] "Export as .CSV" button should be removed
- [x] "Send tokens"button should be added which navigates the user to the "Send tokens" page (which was in the "Payments" menu before)
- [x] Transaction icon (arrow icon) in the transaction section should be changed to user icon. That would be the default icon used for transactions for now.
- [x] “From blockchain address” should be replaced by the blockchain address: truncated, showing the first 9 and last 5 characters, as seen on the design
- [x] If the user clicks anywhere on the transaction row, we should only allow the expand/retract interaction only by clicking in the upper part of the transaction, the first row, this way users can interact with the info below without problems.
- [x] Add a sign in front of each Amount like: +2.123 (color as seen in the design) if it is a credit or -12.23 if it is a debit.
- [x] The time of the transaction should be moved to the the expanded view, above the "Note" section
- [x] Transaction fee should be displayed in the expanded view
- [x] Transaction ID should be displayed fully in the expanded view below the txn fee as seen in the design
- [x] If the transaction is a register name transaction, then "Personalized address registration" transaction type should be used and displayed (as seen in the design). Registered name, time, fee, blockchain addresses, txn id should be displyed as well. 
- [x] Blockchain name and address should be coupled together, the address should be truncated in the middle
- [x] Expand row button (down arrow) is more prominent (see design)
- [x] Send transaction page: Instead of "You send", "Send tokens" should be displayed 
- [x] Send transaction page: New titles: Amount, Note
- [x] Send transaction page: Instead of 3 different sections, the Amount, To and Note sections share the same background. 
- [x] Send transaction page: To section placeholder text should change from "IOV or wallet address" to "Recipient's address"
- [x] Send transaction page: Note section placeholder text should change from "Add a note" to "Add an optional message"
- [x] Transaction confirmation page: Icon change
- [x] Transaction confirmation page: "See transaction" button style removed and only the link remains
- [x] Register name confirmation page: Icon change 
- [x] Register name confirmation page: "Return to balance" button removed

Questions:
- [x] Send transaction page: Note icon should be removed if it doesn't make any sense there
- [x] Send transaction page: Send payment should be changed to Send tokens? Makes more sense in the crypto space?
- [x] How do we display Vote transaction? How do we display Register name transaction? Sender/recipient is different. Should have common fields and specific ones. Transaction ID should be included into the expanded view.
- [x] Amount sorting should be removed from design (we cannot sort for different crypto-currencies, doesn't make sense)

<img width="1440" alt="Transactions Page (1)" src="https://user-images.githubusercontent.com/7419692/66124013-9f08c600-e5e3-11e9-9b69-7fd6f0e2117c.png">

<img width="1440" alt="Transactions Page - Row expanded (1)" src="https://user-images.githubusercontent.com/7419692/66124017-a039f300-e5e3-11e9-9ff6-1bc21e457bce.png">

<img width="1440" alt="Transactions Page - Me to Me edge case (1)" src="https://user-images.githubusercontent.com/7419692/66124024-a203b680-e5e3-11e9-8882-fd67ad8f06cf.png">

<img width="1440" alt="Transactions Page - Personalized address registration (1)" src="https://user-images.githubusercontent.com/7419692/66124030-a29c4d00-e5e3-11e9-8613-8658fa287d99.png">

<img width="1440" alt="Transactions Page - hover transaction id (1)" src="https://user-images.githubusercontent.com/7419692/66124033-a5973d80-e5e3-11e9-9af2-49326ee9e4a5.png">

<img width="1440" alt="Transactions Page - Confirmed transaction" src="https://user-images.githubusercontent.com/7419692/66124037-a7610100-e5e3-11e9-88b4-2e8ceee07ae5.png">

<img width="1440" alt="Transactions Page - Confirmed address registration" src="https://user-images.githubusercontent.com/7419692/66124040-a7f99780-e5e3-11e9-95c9-4773600fbafc.png">

<img width="1440" alt="Transactions Page - Send a Transaction" src="https://user-images.githubusercontent.com/7419692/66118303-51399100-e5d6-11e9-8f48-e59132e211a7.png">

**Comment by annatorok** [comment]
Answers:
- Note icon removed
- Send transaction page: "Send payment" changed to "Send tokens"
- Common fields added for transactions
- Amount sorting removed

**Comment by albertandrejev** [comment]
Do not forget to enable payments E2E tests.
