### ISSUE TITLE
Rename "IOV Wallet" to "Neuma Wallet" everywhere

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#843]
From now on, we should use and refer to the IOV Wallet as Neuma Wallet.

AC:
- [ ] IOV Wallet text is renamed to Neuma Wallet everywhere 
- [ ]  IOV logo is replaced with Neuma logo everywhere regarding the Wallet

**Comment by albertandrejev** [comment]
I need different logo for login screen, with Neuma instead of IOV.
