### ISSUE TITLE
Menu screen modifications

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#848]
Changes:

- [x] Icons are removed from the menu points
- [x] In the title, the menu title will be always displayed. Eg. if the user is in Settings, "Settings" will be displayed as the title
- [x] Menu points were rearranged, at the top menu level, we only have "Requests" and "Settings" and "Log out" menu points
- [x] Neuma logo is displayed on every menu screen
- [x] In the Settings menu, there is: "Networks", "About", "Reveal Seed", "Delete Wallet" menu points
- [x] In the "Networks" menu, the list of connected networks are displayed with the public api endpoint (just like in Metamask)
- [x] In the "About" menu, the version of the extension as well as the support link
- [x] The "Visit our Support Center" link should navigate the user in a new window to https://support.iov.one/hc/en-us/requests/new?ticket_form_id=360000387040
- [x] In the "Reveal Seed" menu, the user can reveal his 12 words phrase. The user has to input his password again to reveal the phrases.
- [x] Reveal Seed screen: Until the user didn't add the password, the "Reveal Seed" button is disabled. Once the password was given, the button changes to an active state.
- [x] "Delete Wallet" screen: text area got a title: "Your recovery words" 
- [x] "Delete Wallet" screen: placeholder text changed to: "Enter your recovery words here" 
- [x] "Delete Wallet" screen: the colour of the "Delete" button changed to red, as well as the text changed to "Delete Wallet" 

![Menu](https://user-images.githubusercontent.com/7419692/67502069-9d339f00-f685-11e9-9883-6db23d2592f0.png)
![Menu - About](https://user-images.githubusercontent.com/7419692/67502058-9c027200-f685-11e9-992a-9edfe57151ee.png)
![Menu - Delete Wallet](https://user-images.githubusercontent.com/7419692/67502060-9c9b0880-f685-11e9-855b-4fba8d7ab90c.png)
![Menu - Networks](https://user-images.githubusercontent.com/7419692/67502061-9c9b0880-f685-11e9-8989-eb1a2b93b101.png)
![Menu - Reveal Seed - Enter password](https://user-images.githubusercontent.com/7419692/67502063-9d339f00-f685-11e9-9b84-f51aac8e79ec.png)
![Menu - Reveal Seed - Seed revealed](https://user-images.githubusercontent.com/7419692/67502064-9d339f00-f685-11e9-93e2-d3846ec304e1.png)
![Menu - Settings](https://user-images.githubusercontent.com/7419692/67502067-9d339f00-f685-11e9-878b-551f61b7c8c4.png)

**Comment by albertandrejev** [comment]
Regarding naming convention: https://github.com/iov-one/ponferrada/issues/687
