### ISSUE TITLE
Redirect wallet.iov.one to wallet.neuma.io

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#853]
**Goal:** we will use the Neuma brand as the name/face for the wallet/extension from now on and we want to use it as THE brand.

We want to therefore use **wallet.neuma.io** instead of wallet.iov.one.

**What to change?**
https://github.com/iov-one/ponferrada/blob/master/packages/sanes-browser-extension/config/manifest-staging.json's `externally_connectable.matches` needs to replace `https://*.iov.one` with `https://*.neuma.io`

**Comment by davepuchyr** [comment]
I intentionally didn't include the redirect for production because I want us to test it in staging first.  What tirggers the depolyment to firebase?

**Comment by albertandrejev** [comment]
@davepuchyr unfortunately we have only brief document how to deploy extension+wallet+governance and I am afraid that following those instructions we can break anything. So I do not want to deploy to staging or to production until Simon will come.

**Comment by davepuchyr** [comment]
It's right to be prudent now that we're live.  I just want to make sure that travis doesn't automagically deploy to firebase.  From what you wrote, I guess it doesn't, so good.  Thanks for the quick reply.
