### ISSUE TITLE
List DAI and USDT stable coin in Neuma Wallet

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#857]
Goal: to list stable coins DAI and USDT in Neuma Wallet

From Will: 

> We should provide a list of ERC20 tokens and their contract addresses when instantiating an `EthereumConnection` instance.

> you can just use the same EthereumConnection as with ETH.
When creating an instance you pass EthereumConnectionOptions: https://github.com/iov-one/iov-core/blob/master/packages/iov-ethereum/src/ethereumconnection.ts#L130-L141
In there you can specify a map of ERC20 token tickers to options (covering eg contract address, decimals etc): https://github.com/iov-one/iov-core/blob/master/packages/iov-ethereum/src/erc20.ts#L25
From there you should be able to use the connection methods relating to ERC20 tokens. Check the tests for example usage. Eg getting an account with ERC20 tokens: https://github.com/iov-one/iov-core/blob/master/packages/iov-ethereum/src/ethereumconnection.spec.ts#L302-L314
Or sending ERC20 tokens: https://github.com/iov-one/iov-core/blob/master/packages/iov-ethereum/src/ethereumconnection.spec.ts#L596-L644

- [x] Add ERC20 coins support
- [x] Implement Unit testing

**Comment by webmaster128** [comment]
This has already been proven to work in the wallet-demo project and is relatively easy to do.

But just to make sure we're on the same page what implications this has: As soon as we support for a given ERC20 token on the mainnet we need to assume that some of our users hold that token and we cannot remove support for that token anymore without a massive migration camapign. For this reason we should be very careful and selective when it comes to adding mainnet ERC20s. cc @BenSim

**Comment by albertandrejev** [comment]
Do not merge until #866 decision will be made.
