### ISSUE TITLE
Activate redirect wallet.iov.one -> wallet.neuma.io

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#869]
Neuma 1.1.x with the extended domain whitelist needs released. We should also wait some time to make sure the majority or our users have upgraded.

--------

- [x] wallet-staging.iov.one -> wallet-staging.neuma.io
- [x] wallet.iov.one -> wallet.neuma.io

**Comment by webmaster128** [comment]
The updated domain whitelist was deployed to production with the v1.1.0 tag on 2019-11-27. We have no information about the browser extension upgrade speed of our users. Let's drink some tee and wait.

**Comment by annatorok** [comment]
Let's wait another week and then release this.
