### ISSUE TITLE
Configure staging faucet

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#885]
There is a faucet for Dancenet (staging) available at https://faucet.x-dancenet.iov.one/. The wallet should be configured to use it.

**Comment by albertandrejev** [comment]
Can continue only after https://github.com/iov-one/ponferrada/pull/889 implementation.

**Comment by webmaster128** [comment]
Why is this blocked by #889? The only thing that is needed is a config entry like https://github.com/iov-one/ponferrada/blob/v1.1.1-alpha.0/packages/bierzo-wallet/src/config/development.json#L20-L23 for `staging.json`.

**Comment by albertandrejev** [comment]
Yes, now it is not blocked after https://github.com/iov-one/ponferrada/pull/889#discussion_r353102988 :)
