### ISSUE TITLE
Extension link incorrect for staging config

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#942]
The extension link in https://github.com/iov-one/ponferrada/blob/v1.1.1-alpha.4/packages/bierzo-wallet/src/config/staging.json#L3 should be the staging extension. But it is the production extension right now.

**Comment by albertandrejev** [comment]
Wrong link was used in the config file. 
We should use https://chrome.google.com/webstore/detail/neuma-staging/ililemcipflfijjbkniehikepfpdgail instead
