### ISSUE TITLE
Ability to edit RPC url to Neuma extension for IOV testnet

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#947]
**Goal:**
In the future, we want our dev team to easily test their new application integrations with Neuma and for that, it would be great to add a functionality for the Neuma extension, so a new custom RPC url can be added manually.

- [x] it is possible to add custom RPC url in staging extension for IOV testnet (basically changing the RPC url for the existing IOV testnet)
- [x] editing the RPC url will change the RPC url for IOV testnet
- [x] Two fields are needed for editing a new RPC url: "Network Name" which is prepopulated from the already given one (something like IOV Dancenet, or similar) and prepopulated "New RPC Url"
- [x] "Cancel" and "Save" buttons are shown after the two fields - "Save" will save all the changes, Cancel will go back to the previous screen to the Networks
- [x] below the IOV testnet RPC url, there is a "Change" text which will navigate the user to the two fields previously mentioned in a new screen

![Menu - Networks - Change Network - Empty field](https://user-images.githubusercontent.com/7419692/71961170-1c516180-31f7-11ea-81b8-fb1826816963.png)
![Menu - Networks - Change Network](https://user-images.githubusercontent.com/7419692/71961173-1d828e80-31f7-11ea-94bd-6fe56dca0232.png)
![Menu - Networks (1)](https://user-images.githubusercontent.com/7419692/71961176-1eb3bb80-31f7-11ea-8de2-74a8a42ce5e6.png)

If you check Metamask, there is already a feature like this.

![Screenshot 2020-01-07 at 12 15 37](https://user-images.githubusercontent.com/7419692/71891729-84e10580-3147-11ea-9005-315b44879fc1.png)
![Screenshot 2020-01-07 at 12 15 43](https://user-images.githubusercontent.com/7419692/71891730-84e10580-3147-11ea-91b2-23b3dfb5a46e.png)

**Comment by abefernan** [comment]
I have checked that this is not possible. When a user logs in, 3 things happen:

- The user accounts are loaded: it gets a BNS connection in order to get the accounts.
- The user balances are loaded: it uses the accounts loaded before.
- The user starnames are loaded: it gets a BNS connection in order to get the starnames.

The BNS connection needs the IOV network to be up.

**Comment by albertandrejev** [comment]
This task should be splitted:
- [*] Apply changes to the extension (PR #970)
- [ ] Load supported chans list from the extension
