### ISSUE TITLE
Test wallet improvement in staging environment - Part 1

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#949]
- [x] test ERC20 tokens on staging to make sure it works
- [x] test wallet improvements in staging

**Comment by abefernan** [comment]
Wallet:

- If you click on a network, and then on remove, then everything works unexpectedly. It does not let you select the available networks and it does not render their forms.

- There are network names that do not fit the select button (e.g. IOV Dancenet).
![image](https://user-images.githubusercontent.com/44572727/72597659-798f9600-390e-11ea-8153-3f480a37ab18.png)

- We only allow one address per network, but a user can click keep adding "Select" network forms beyond the number of available networks.
![image](https://user-images.githubusercontent.com/44572727/72597682-84e2c180-390e-11ea-89af-d52b3705963f.png)

Extension:

- When opened, is unresponsive and blank for 2 seconds.

**Comment by albertandrejev** [comment]
* https://github.com/iov-one/ponferrada/issues/958
* https://github.com/iov-one/ponferrada/issues/957
* https://github.com/iov-one/ponferrada/issues/956
