### ISSUE TITLE
ThemeProvider and redux and react-router in bierzo-wallet

### ISSUE THREAD

**Issue by apanizo** [iov-one/ponferrada#95]
The Bierzo wallet project will use redux for handling routes, also because it is going to be a webapp maintained by us, should use the general react components and styles provided in `medulas-react-components`, so, for reusing styles we should inject `MedulasThemeProvider` .

- [x] Use of ThemeProvider
- [x] Install redux
- [x] Install react-router

**Comment by kmw101** [comment]
Issue is done
