### ISSUE TITLE
Network names too big don't fit

### ISSUE THREAD

**Issue by abefernan** [iov-one/ponferrada#959]
Bug found in the testing of staging as part of #949.

There are network names that do not fit the select button (e.g. IOV Dancenet):
![image](https://user-images.githubusercontent.com/44572727/72599932-eefd6580-3912-11ea-9cf9-8929180a4d2d.png).

**Comment by albertandrejev** [comment]
To be honest I do not think that this is a bug. Because we can not predict possible length of the token name. Also this is standard select component behaviour to show item during selection and then crop it when it was selected. @abefernan @annatorok

**Comment by albertandrejev** [comment]
@abefernan @annatorok

**Comment by abefernan** [comment]
> To be honest I do not think that this is a bug. Because we can not predict possible length of the token name. Also this is standard select component behaviour to show item during selection and then crop it when it was selected. @abefernan @annatorok

Ok, the name is fully shown in the dropdown list. The only issue I can think of is if 2 networks have a similar name in the beginning and you wouldn't know which one you are editing... but does not have an obvious fix.

**Comment by annatorok** [comment]
@abefernan that's fine for now, thanks.
