### ISSUE TITLE
User is not navigated to log in screen

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#964]
If the user is leaving the wallet tab in the browser for approx 15mins or more and then returns to the wallet tab, the user won't be able to do anything in the Wallet (eg. register a name) and the Wallet doesn't give any feedback why nothing is working (when trying to register a name, the action just hangs and there is a loading icon displayed forever).

Ideally, we want to navigate the user to the log in screen or somehow display that the session timed out.

![Screenshot 2020-01-17 at 12 24 00](https://user-images.githubusercontent.com/7419692/72610405-8a003a80-3927-11ea-82ab-62c9d51d8d6d.png)

**Comment by albertandrejev** [comment]
There is no session timeout.  Symptoms you was talking about looks like there was problem with code and application hangs. This is SPA and there is no backend what can produce session timeout. Not in our case.

**Comment by annatorok** [comment]
Maybe it was an issue with the extension? I left the wallet tab in the browser there for 20 mins and when I tried to register a new name, everything was working well.

**Comment by webmaster128** [comment]
The wallet uses Websocket connections to the blockchain nodes. Once they break, the wallet does not work anymore. Currently there is no functional reconnect nor error reporting when that happens.
