### ISSUE TITLE
Extension policy needs to be accessible without login

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#988]
We want to update the extension in the Chrome Store, however the process failed because the privacy policy is not visible without login.

In order for Google not the reject any update for the chrome extension, we need to make the privacy policy available for everyone, without logging in.

- [x] https://neuma.io/policy site is available for users without the need to logging in on neuma.io
- [x] add the Policy's page link to the Welcome screen of the extension. Text should be: Privacy policy

![Screenshot 2020-01-27 at 10 30 56](https://user-images.githubusercontent.com/7419692/73163389-32648a80-40f0-11ea-8d6f-4d164ea9a12d.png)

**Comment by abefernan** [comment]
Closed by #989 and by the availability of neuma.io/policy

**Comment by abefernan** [comment]
Closed by #989 and by the availability of neuma.io/policy
